# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akirachix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='Good student'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='names',
            field=models.CharField(max_length=100),
        ),
    ]
